config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profile', to: 'buyers#profile'
  get 'seller_home', to: 'sellers#seller_home'
  get 'pages', to: 'pages#about_us'

  resources :buyers, only: [ :new, :create, :update ]

  resources :sellers do
    collection do
      get :bam
      get :before_july
      get :molby
    end
    resources :sustainability_practices, only: [ :new, :create, :edit, :update ]
  end

  resources :listings, only: [ :new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      # featured on home page
      get :new_in
      get :activewear
      get :denim
      get :jackets
      get :day_dresses
      # others on nav bar
      get :dresses
      get :tops
      get :trousers
      get :skirts
      get :accessories
    end
  end

  resources :orders, only: [:show, :create, :index] do
    resources :payments, only: :new
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :index, :show ]
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :seller
  has_one :order
  has_one_attached :photo

  monetize :price_cents, numericality: {less_than: 20000}

  validates :title, presence: true, length: { in: 3..100 }
  validates :category, presence: true, inclusion: { in: %w[dresses tops outerwear bottoms shoes accessories activewear] }
  validates :subcategory, presence: true, inclusion: { in: ["evening dresses", "day dresses", "blouses", "tshirts", "camisoles", "knitwear", "coats", "jackets", "trousers", "jeans", "skirts", "shorts", "boots", "sandals", "trainers", "loafers", "jewellery", "scarves", "hair accessories", "bags", "leggings", "gym tops", "sports bras"] }
  validates :price, presence: true, numericality: {less_than: 200}
  validates :size, presence: true, inclusion: { in: %w[XS S M L UK6 UK8 UK10 UK12 UK14 UK16 UK18 UK20 UK3/EU36 UK4/EU37 UK5/EU38 UK6/EU39 UK7/EU40 UK8/EU41 UK9/EU42 One\ Size], message: "not a valid size" }
  validates :description, presence: true, length: { in: 3..1000 }
  # validates :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_details,
    against: [ :title, :category, :subcategory, :description, :size ],
    associated_against: {
      seller: [ :shop_name ]
    },
    using: {
      tsearch: { prefix: true } # partial words (beginning) can be searched
    }

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, except: [:new, :create, :update]

  def index
    if params[:query].present?
      @listings = Listing.search_by_details(params[:query]).where(sold: false)
    else
      @listings = Listing.where(sold: false)
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.seller = current_user.seller
    if @listing.save
      redirect_to seller_home_path
    else
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to seller_home_path
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to seller_home_path
  end

  # categories - non CRUD methods - could refactor category & subcategory listings

  def new_in
    shuffled_listings = Listing.where(sold: false).shuffle
    @listings = shuffled_listings.first(15)
  end

  def activewear
    @listings = Listing.where(category: "activewear", sold: false)
  end

  def denim
    @listings = Listing.where(subcategory: "jeans", sold: false)
  end

  def jackets
    @listings = Listing.where(category: "outerwear", sold: false)
  end

  def day_dresses
    @listings = Listing.where(subcategory: "day dresses", sold: false)
  end

  def dresses
    @listings = Listing.where(category: "dresses", sold: false)
  end

  def tops
    @listings = Listing.where(category: "tops", sold: false)
  end

  def trousers
    @listings = Listing.where(subcategory: "trousers", sold: false)
  end

  def skirts
    @listings = Listing.where(subcategory: "skirts", sold: false)
  end

  def accessories
    @listings = Listing.where(category: "accessories", sold: false)
  end

  private

  def listing_params
    params.require(:listing).permit(:seller, :title, :category, :subcategory, :price, :size, :description, :in_basket, :photo)
  end

end

app/views/listings/_form.html.erb
  <%= simple_form_for(@listing) do |f| %>
    <%= f.input :title %>
    <%= f.input :category, collection: %w[dresses tops outerwear bottoms shoes accessories activewear] %>
    <%= f.input :subcategory, collection: ["evening dresses", "day dresses", "blouses", "tshirts", "camisoles", "knitwear", "coats", "jackets", "trousers", "jeans", "skirts", "shorts", "boots", "sandals", "trainers", "loafers", "jewellery", "scarves", "hair accessories", "bags", "leggings", "gym tops", "sports bras"] %>
    <%= f.input :size, collection: %w[XS S M L UK6 UK8 UK10 UK12 UK14 UK16 UK18 UK20 UK3/EU36 UK4/EU37 UK5/EU38 UK6/EU39 UK7/EU40 UK8/EU41 UK9/EU42 One\ Size] %>
    <%= f.input :price, placeholder: 3, label:'Price £ (Less than £200)' %>
    <%= f.input :description, label:'Item description', placeholder: "Include materials composition, washing instructions if applicable" %>
    <%= f.input :photo, as: :file, label:'Add a photo' %>
    <%= f.submit 'Submit', class:"button" %>
  <% end %>

app/views/listings/accessories.html.erb
<div class="container feature">
  <h2 class="page-title">Accessories</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/activewear.html.erb
<div class="container activewear">
  <h2 class="page-title">Activewear</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/day_dresses.html.erb
<div class="container feature">
  <h2 class="page-title">Day Dresses</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/denim.html.erb
<div class="container">
  <h2 class="page-title">Classic denim</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/dresses.html.erb
<div class="container feature">
  <h2 class="page-title">Dresses</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/index.html.erb
<div class="container search">
  <%# <h2 class="page-title">Search all items</h2> %>

  <%= form_tag listings_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Search all items"
    %>
    <%= button_tag :submit, class:"search-button" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>

  <%= render 'shared/listing_card', collection: @listings %>
  <% if @listings.empty? %>
    <p>Sorry no items found, sellers are constantly adding new items so please check back soon.</p>
    <%= link_to "Back to all items", listings_path, class:"search-again" %>
  <% end %>

</div>

app/views/listings/jackets.html.erb
<div class="container feature">
  <h2 class="page-title">Jackets and coats</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/new.html.erb
<div class="container listing-new">
  <h2 class="page-title">List a New Item</h2>

  <h5>Add item details:</h5>
  <%= render "form", listing: @listing %>

</div>

app/views/listings/new_in.html.erb
<div class="container new-in">
  <h2 class="page-title">New In</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/show.html.erb
<div class="container listing-show">

  <%= cl_image_tag @listing.photo.key %>

  <div class="listing-info">

    <div class="key-info">
      <h4><%= @listing.title %></h4>
      <h5>£<%= @listing.price.round() %></h5>
      <h5>Available in: <%= @listing.size %></h5>

      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'listing_id', @listing.id %>
        <%= submit_tag 'Buy Now', class: 'button' %>
      <% end %>

      <p><%= @listing.description %></p>
    </div>

    <div class="seller-details">
      <h5>Sold by <%= @listing.seller.shop_name %></h5>
      <div class="sustainability">
        <p>Sustainability practices:</p>
        <ul>
          <li><i class="fas fa-leaf"></i> Materials that minimise harm to the environment</li>
          <li><i class="fas fa-leaf"></i> Waste is eliminated along the supply chain</li>
          <li><i class="fas fa-leaf"></i> Emissions are minimised throughout the supply chain</li>
          <li><i class="fas fa-leaf"></i> Packaging is recyclable or made from sustainable materials</li>
        </ul>
      </div>

      <%= link_to seller_path(@listing.seller) do %>
        <strong><p>See more from  <%= @listing.seller.shop_name %></p></strong>
      <% end %>
    </div>

  </div>

</div>

app/views/listings/skirts.html.erb
<div class="container feature">
  <h2 class="page-title">Skirts</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/tops.html.erb
<div class="container feature">
  <h2 class="page-title">Tops</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/listings/trousers.html.erb
<div class="container feature">
  <h2 class="page-title">Trousers</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>