config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profile', to: 'buyers#profile'
  get 'seller_home', to: 'sellers#seller_home'
  get 'pages', to: 'pages#about_us'

  resources :buyers, only: [ :new, :create, :update ]

  resources :sellers do
    collection do
      get :bam
      get :before_july
      get :molby
    end
    resources :sustainability_practices, only: [ :new, :create, :edit, :update ]
  end

  resources :listings, only: [ :new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      # featured on home page
      get :new_in
      get :activewear
      get :denim
      get :jackets
      get :day_dresses
      # others on nav bar
      get :dresses
      get :tops
      get :trousers
      get :skirts
      get :accessories
    end
  end

  resources :orders, only: [:show, :create, :index] do
    resources :payments, only: :new
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :index, :show ]
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :orders, through: :listings
  has_one :sustainability_practice

  validates :shop_name, presence: true, uniqueness: true
  validates :shop_description, presence: true, length: { in: 3..100 }
  validates :user, presence: true
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @seller = Seller.find(params[:id])
    @listings = Listing.where(seller: @seller, sold: false)
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(seller_params)
    @seller.user = current_user
    if @seller.save
      redirect_to seller_home_path
    else
      render :new
    end
  end

  def update
    @seller = Seller.find(params[:id])
    @seller.update(seller_params)

    respond_to do |format|
      format.html { redirect_to seller_home_path, notice: 'Details updated!' }
      format.json { head :no_content }
    end
  end

  def seller_home
    @seller = current_user.seller
    @listings = Listing.where(seller: @seller, sold: false)
    @sales = Listing.where(seller: @seller, sold: true)
    @sales_value = 0
    @sales.each do |sale|
      @sales_value += sale.price
    end
  end

  def bam
    seller = Seller.find_by_shop_name("BAM")
    @listings = Listing.where(seller: seller)
  end

  def molby
    seller = Seller.find_by_shop_name("Molby the Label")
    @listings = Listing.where(seller: seller)
  end

  def before_july
    seller = Seller.find_by_shop_name("Before July")
    @listings = Listing.where(seller: seller)
  end

  private

  def seller_params
    params.require(:seller).permit(:user, :shop_name, :shop_description)
  end
end

app/views/sellers/bam.html.erb
<div class="container feature">
  <h2 class="page-title">All Items Sold by BAM</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/sellers/before_july.html.erb
<div class="container feature">
  <h2 class="page-title">All Items Sold by Before July</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/sellers/molby.html.erb
<div class="container feature">
  <h2 class="page-title">All Items Sold by Molby the Label</h2>

  <%= render 'shared/listing_card', collection: @listings %>

</div>

app/views/sellers/new.html.erb
<div class="container seller-new">
  <h2 class="page-title">Create your seller profile</h2>

  <h5>Add your shop details:</h5>
  <%= simple_form_for(@seller) do |f| %>
    <%= f.input :shop_name %>
    <%= f.input :shop_description, placeholder: "A sentence or two best describing your shop" %>
    <%= f.submit 'Submit', class:"button" %>
  <% end %>

</div>

app/views/sellers/seller_home.html.erb
<div class="container seller-home">
  <h2 class="page-title">Seller Homepage</h2>

  <strong>
    <%= link_to seller_path(@seller), class:"seller-home-link" do %>
      <h5>See customer view of <%= @seller.shop_name %>'s page</h5>
    <% end %>
  </strong>

  <h3>My Details</h3>

    <div class="seller-details" data-controller="edit-seller">
      <div class="seller-detail">
        <p  data-edit-seller-target="name">Shop Name: <%= @seller.shop_name %></p>
        <%# MAKE THIS A LINK TO EDIT %>
        <i class="far fa-edit" data-edit-seller-target="nameIcon" data-action="click->edit-seller#displayNameForm"></i>
        <%= simple_form_for @seller, html: { class: "d-none", data: { edit_seller_target: "nameForm", action: "submit->edit-seller#update" } } do |f| %>
          <%= f.input :shop_name, label:'Shop Name:' %>
          <%= f.submit 'Update', class:"button" %>
        <% end %>
      </div>
      <div class="seller-detail">
        <p  data-edit-seller-target="desc">Shop Description: <%= @seller.shop_description %> </p>
         <%# MAKE THIS A LINK TO EDIT %>
        <i class="far fa-edit" data-edit-seller-target="descIcon" data-action="click->edit-seller#displayDescForm"></i>
        <%= simple_form_for @seller, html: { class: "d-none", data: { edit_seller_target: "descForm", action: "submit->edit-seller#update" } } do |f| %>
          <%= f.input :shop_description, label:'Shop Description:' %>
          <%= f.submit 'Update', class:"button" %>
        <% end %>
      </div>
    </div>

  <%# add edit details and listings, delete listings functionality %>

  <h3>My Listings (<%= @listings.count %>)</h3>
  <div class="listings">
    <strong><%= link_to "List a new item", new_listing_path(@seller), class:"button add-listing" %></strong>

    <% if @listings.empty? %>
      <p>You haven't listed any items yet.</p>
    <% else %>
      <div class="order-cards">
        <% @listings.each do |listing| %>
          <div class="order-card">
              <%= cl_image_tag listing.photo.key %>
              <div class="order-card-infos">
                <strong><p><%= listing.title %> - <%= listing.size %></p></strong>
                <p class="description"><%= listing.description %></p>
                <p>£<%= listing.price.round() %></p>
                <em>
                  <p class="dates">Last updated on <%= listing.updated_at.to_date.strftime("%d %b %Y") %></p>
                </em>
                <%= link_to listing_path(listing), method: :delete, data: { confirm: "Are you sure you want to delete this item?" } do %>
                  <i class="far fa-trash-alt delete"></i>
                <% end %>
                <%= link_to edit_listing_path(listing) do %>
                  <i class="far fa-edit edit"></i>
                <% end %>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>


  <h3>My Sales (<%= @sales.count %>)</h3>
  <div class="sales">
    <% if @sales.empty? %>
      <p>You haven't sold any items yet.</p>
    <% else %>
      <p>Total sales: £<%= @sales_value.round() %></p>
      <div class="order-cards">
        <% @sales.each do |listing| %>
          <div class="order-card">
              <%= cl_image_tag listing.photo.key %>
              <div class="order-card-infos">
                <strong><p><%= listing.title %> - <%= listing.size %></p></strong>
                <p>Sold to <%= listing.order.buyer.user.username %></p>
                <p>Dispatch address: <%= listing.order.buyer.address %></p>
                <p>£<%= listing.price.round() %></p>
                <em>
                  <p class="dates">Sold on <%= listing.order.updated_at.to_date.strftime("%d %b %Y") %></p>
                </em>
              </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>


</div>

app/views/sellers/show.html.erb
<div class="container feature">
  <h2 class="page-title"><%= @seller.shop_name %></h2>

  <p><%= @seller.shop_description %></p>

  <%# about them (description) %>
  <%# sustainability values %>
  <%# listings %>
  <%# contact them %>

  <%= render 'shared/listing_card', collection: @listings %>

</div>