config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profile', to: 'buyers#profile'
  get 'seller_home', to: 'sellers#seller_home'
  get 'pages', to: 'pages#about_us'

  resources :buyers, only: [ :new, :create, :update ]

  resources :sellers do
    collection do
      get :bam
      get :before_july
      get :molby
    end
    resources :sustainability_practices, only: [ :new, :create, :edit, :update ]
  end

  resources :listings, only: [ :new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      # featured on home page
      get :new_in
      get :activewear
      get :denim
      get :jackets
      get :day_dresses
      # others on nav bar
      get :dresses
      get :tops
      get :trousers
      get :skirts
      get :accessories
    end
  end

  resources :orders, only: [:show, :create, :index] do
    resources :payments, only: :new
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :index, :show ]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <hr>
  <div class="container">
    <div class="social-icons">
      <i class="fab fa-instagram"></i>
      <i class="fab fa-facebook-f"></i>
      <i class="fab fa-pinterest-p"></i>
      <i class="fab fa-twitter"></i>
    </div>

    <div data-controller="newsletter-form">
      <h5><strong data-action="click->newsletter-form#unhide">Subscribe</strong> to our newsletter and get 10% off.</h5>

      <div class="newsletter-form-popup d-none" data-newsletter-form-target="form">
        <i class="fas fa-times" data-action="click->newsletter-form#close"></i>
        <form action="">
          <p>Keep up with our latest news and seller additions.</p>
          <p>All new subscribers get 10% off their first purchase.</p>
          <input type="text" placeholder="Your email" name="email" required>
          <button type="submit" class="newsletter-btn">Submit</button>
        </form>
      </div>
    </div>

    <div class="footer-links">
      <%= link_to "About us", pages_path %>
      <br>
      <%= mail_to "mampan@test.com", "Contact us"%>
    </div>

  </div>
</div>

app/views/shared/_listing_card.html.erb
<div class="listing-cards">
  <% @listings.each do |listing| %>
    <%= link_to listing_path(listing) do %>
      <div class="listing-card">
          <%= cl_image_tag listing.photo.key %>
          <div class="listing-text">
            <h5><%= listing.title %></h5>
            <p class="shop-name"><em>Sold by <%= listing.seller.shop_name %></em></p>
            <div class="size-price">
              <p><%= listing.size %></p>
              <p>£<%= listing.price.round() %></p>
            </div>
          </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
            <%= image_tag  "avatar_logo.png", class: "logo dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
              <%# add the logic%>
              <%= link_to "New in", new_in_listings_path, class: "dropdown-item" %>
              <%= link_to "Search", listings_path, class: "dropdown-item" %>
              <%# <p>By Cateogry</p> %>
              <%= link_to "Dresses", dresses_listings_path, class: "dropdown-item category" %>
              <%= link_to "Tops", tops_listings_path, class: "dropdown-item category" %>
              <%= link_to "Trousers", trousers_listings_path, class: "dropdown-item category" %>
              <%= link_to "Jeans", denim_listings_path, class: "dropdown-item category" %>
              <%= link_to "Skirts", skirts_listings_path, class: "dropdown-item category" %>
              <%= link_to "Jackets and Coats", jackets_listings_path, class: "dropdown-item category" %>
              <%= link_to "Activewear", activewear_listings_path, class: "dropdown-item category" %>
              <%= link_to "Accessories", accessories_listings_path, class: "dropdown-item category" %>
              <%= link_to "About us", pages_path, class: "dropdown-item" %>
            </div>
          </li>
    </ul>
  </div>

  <div id="nav-title">
    <h1>
      <%= link_to "MAMPAN", root_path %>
    </h1>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        <%# </li> %>
        <li class="nav-item dropdown">
          <%= image_tag "burger.png", class: "burger-menu dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if !current_user.buyer.nil? %>
              <%= link_to "Profile", profile_path, class: "dropdown-item category" %>
            <% end %>
            <% if current_user.seller.nil? %>
              <%= link_to "Become a Seller", new_seller_path, class: "dropdown-item category" %>
            <% else %>
              <%= link_to "Seller Home", seller_home_path, class: "dropdown-item category" %>
            <% end %>
            <%= link_to "About us", pages_path, class: "dropdown-item category" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new_user.html.erb
<% if current_user == nil %>
  <div class="new-user">
    <p>New here?</p>
    <%= link_to "sign up", new_user_registration_path %>
    <p> or </p>
    <%= link_to "read about us", pages_path %>
  </div>
<% end %>