config/routes.rb
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  devise_for :users, controllers: { registrations: "registrations" }

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'profile', to: 'buyers#profile'
  get 'seller_home', to: 'sellers#seller_home'
  get 'pages', to: 'pages#about_us'

  resources :buyers, only: [ :new, :create, :update ]

  resources :sellers do
    collection do
      get :bam
      get :before_july
      get :molby
    end
    resources :sustainability_practices, only: [ :new, :create, :edit, :update ]
  end

  resources :listings, only: [ :new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      # featured on home page
      get :new_in
      get :activewear
      get :denim
      get :jackets
      get :day_dresses
      # others on nav bar
      get :dresses
      get :tops
      get :trousers
      get :skirts
      get :accessories
    end
  end

  resources :orders, only: [:show, :create, :index] do
    resources :payments, only: :new
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [ :index, :show ]
end

app/views/pages/about_us.html.erb
<div class="container about-us">
  <h2 class="page-title">About Us</h2>

  <h3>What do we do?</h3>
  <div class="about-us-info">
    <img src="https://images.unsplash.com/photo-1541779408-c355f91b42c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80" alt="lady in a blazer, sitting amongst trees">
    <p>Mampan means sustainable in Malay.</p>
    <p>We provide a platform for sustainable fashion brands to sell any production samples and 'old' season stock at affordable prices, reducing waste.</p>
    <p>This means you can browse slow, eco friendly brands all in one marketplace, making it easier for planet-conscious fashion lovers to find that treasure.</p>
    <p>We believe that what you wear shouldn't be restricted to fleeting trends - wear what you love and what makes you feel good.</p>
    <p>Personally, we're a huge fan of vintage-inspired prints paired with classic basics, in easy-to-wear silhouettes.</p>
  </div>

  <h3>How does Mampan work?</h3>

  <%# make two tabs? %>

  <div class="about-us-info">
    <img src="https://images.unsplash.com/photo-1533037625542-6a0b03812a95?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80" alt="lady sitting in the sun, with tropical trees in the background">
    <h5>I'm a customer</h5>
    <p>Browse and enjoy!</p>
    <p>Items are purchased individually, because of the marketplace nature of Mampan's offering.</p>
    <p>Distribution is the responsibility of the seller - please contact the seller with any questions about shipping, exchanges and returns.</p>
  </div>

  <div class="about-us-info">
    <img src="https://images.unsplash.com/photo-1614990354198-b06764dcb13c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1331&q=80" alt="vintage shirts hanging on a rack">
    <h5>I'm a seller</h5>
    <p>Sign up and list your items!</p>
    <p>Items must adhere to at least one of our sustainability measures and fall in an affordable price range.</p>
    <p>Distribution is the responsibility of the seller.</p>
  </div>

  <p>If you have any questions, please contact us at <strong><em>mampan@test.com</em></strong></p>

</div>

app/views/pages/home.html.erb
<div class="container homepage">

    <div class="new-in-cards">
      <div class="homepage-story" id="new-in">
        <%= link_to new_in_listings_path do %>
          <h2>New in</h2>
          <p>Browse the latest drops from our sustainable sellers</p>
        <% end %>
      </div>

      <%= link_to accessories_listings_path, class:"homepage-video" do %>
        <%= video_tag "hat_video.mp4", autoplay: true, loop: true, muted: true, controls: false, playsinline: true %>
        <div class="overlay-text">
          <h3>Jump for joy, Spring accessories are here!</h3>
        </div>
      <% end %>
    </div>

    <div class="homepage-story" id="activewear">
      <%= link_to activewear_listings_path do %>
        <h2>Focus On: Activewear</h2>
        <p>Work out in style</p>
      <% end %>
    </div>

  <div class="homepage-carousels">

    <div>
      <h2>What's Popular</h2>

      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

          <div class="carousel-item active">
            <img class="d-block w-100" src="https://images.unsplash.com/flagged/photo-1554033750-2137b5cfd7ce?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1978&q=80" alt="Coats and jackets">
            <%= link_to jackets_listings_path do %>
              <div class="carousel-caption">
                <h3>Coats and Jackets</h3>
              </div>
            <% end %>
          </div>

          <div class="carousel-item">
            <img class="w-100" src="https://images.unsplash.com/photo-1516810773736-19a71ee11dab?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1887&q=80" alt="Knitwear">
            <%= link_to denim_listings_path do %>
              <div class="carousel-caption">
                <h3>Classic Denim</h3>
              </div>
            <% end %>
          </div>

          <div class="carousel-item">
            <img class="w-100" src="https://images.unsplash.com/photo-1532675432006-329c6fed7045?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1854&q=80" alt="Midi dress">
            <%= link_to day_dresses_listings_path do %>
              <div class="carousel-caption">
                <h3>Day Dresses</h3>
              </div>
            <% end %>
          </div>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div>
      <h2>Featured Sellers</h2>

      <div id="carouselExampleControls2" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

          <div class="carousel-item active">
            <%= image_tag "bamboo.png", class:"d-block w-100", alt:"Back view of lady wearing yoga bra and leggings, stretching to the side" %>
            <%= link_to bam_sellers_path do %>
              <div class="carousel-caption">
                <h3>BAM</h3>
                <p>Natural activewear</p>
              </div>
            <% end %>
          </div>

          <div class="carousel-item">
            <%= image_tag "before_july.png", class:"d-block w-100", alt:"Green puff sleeve crop top with cow print high waisted jeans" %>
            <%= link_to before_july_sellers_path do %>
              <div class="carousel-caption">
                <h3>Before July</h3>
                <p>Timeless statement pieces</p>
              </div>
            <% end %>
          </div>

          <div class="carousel-item">
            <%= image_tag "molby.png", class:"d-block w-100", alt:"Back view of lady wearing beige and black seersucker gingham dress and matching hair bow" %>
            <%= link_to molby_sellers_path do %>
              <div class="carousel-caption">
                <h3>Molby the Label</h3>
                <p>Handmade British slow fashion</p>
              </div>
            <% end %>
          </div>

        </div>

        <a class="carousel-control-prev" href="#carouselExampleControls2" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls2" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

  </div>

</div>